### ISSUE TITLE
Issues

### ISSUE THREAD

**Issue by vr8hub** [jdecock/edgar-rice-burroughs_the-return-of-tarzan#1]
- [x] We need to improve the manual on this, but I haven't had time to submit a PR yet; e.g., _douar_ is in the M-W _unabridged_ dictionary, which does not count as being "in M-W". (Notice the light-blue offset below the definition that begins "You must love words.") Since it doesn't appear in (the regular) M-W, then it should be italicized. _However_, in this particular case, the word has so many occurrences that it falls into section [8.2.9.3](https://standardebooks.org/manual/1.6.2/single-page#8.2.9.3), i.e. it occurs so often that we only italicize the first occurrence. So, you should italicize the first occurrence and leave the rest as spans. I know, the long way around to say italicize the first occurrence, but I wanted you to know why. :)
- [x] The other foreign words that are in M-W (if they are in the "regular" M-W and don't have the above offset on them), e.g. kopje, spahi, do not need spans. The reason we use language tags is to help pronunciation on readers; if the word is in M-W (i.e. "the dictionary"), then no extra help is needed, since it has the correct pronunciation. Section 8.2.9.2 mentions using spans, but those are only for foreign titles or proper names, and only if they would not normally be pronounced correctly.
- [x] Likewise, I'm not sure the x-mangani tags are necessary, because I believe those words will be pronounced correctly with or without them. But, I'm not sure about those, so I'll let @acabal weigh in. ("Numa", "Bolgani", "Tantor", "Sabor", "Horta", "Sheeta", "Histah", Alex, all words used as "names" of animals by Tarzan.)
- [x] The long description looks like it might be missing a word? Should "as Tarzan travelling to France" be "as Tarzan _is_ travelling to France"? (without the italics, obviously) Also, traveling only has one L in the US.

**Comment by acabal** [comment]
Names don't get language tags because names are typically unique sounds, and not grammatical language per se
